---
- name: Install dumb init
  get_url: dest=/usr/bin/dumb-init url=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 mode=0775 validate_certs=no
- name: Install EPEL
  yum: name=epel-release state=latest update_cache=yes
- name: Install redis
  yum: name=redis state=latest
- name: Make redis config
  template: src=redis.conf dest=/etc/redis.conf
